name = "AMOCStochasticBoxModel"
uuid = "34280833-7464-4a64-9447-0997507d7aea"
authors = ["Matt Graham <matthew.m.graham@gmail.com> and contributors"]
version = "0.1.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
